//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SignStudyHour
    {
        public int StudyHoursId { get; set; }
        public string GuyId { get; set; }
        public System.DateTime Date { get; set; }
        public int LongStudy { get; set; }
        public int StudyId { get; set; }
    
        public virtual Guy Guy { get; set; }
        public virtual StudyHour StudyHour { get; set; }
    }
}
