//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMERS_TBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUSTOMERS_TBL()
        {
            this.ORDERS_TBL = new HashSet<ORDERS_TBL>();
        }
    
        public string CUSTID { get; set; }
        public string CUSTNAME { get; set; }
        public string custaddress { get; set; }
        public string CUSTCITY { get; set; }
        public string CUSTPHONE { get; set; }
        public string CUSTFAX { get; set; }
        public string EMPID { get; set; }
    
        public virtual EMPLOYEE_TBL EMPLOYEE_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERS_TBL> ORDERS_TBL { get; set; }
    }
}
