//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE_PAY_TBL
    {
        public int payid { get; set; }
        public string EMPID { get; set; }
        public Nullable<decimal> payrate { get; set; }
        public Nullable<System.DateTime> datelastraise { get; set; }
        public Nullable<decimal> SALARY { get; set; }
        public Nullable<decimal> bonus { get; set; }
    
        public virtual EMPLOYEE_TBL EMPLOYEE_TBL { get; set; }
    }
}
