//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmployeeEntities : DbContext
    {
        public EmployeeEntities()
            : base("name=EmployeeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CUSTOMERS_TBL> CUSTOMERS_TBL { get; set; }
        public virtual DbSet<EMPLOYEE_PAY_TBL> EMPLOYEE_PAY_TBL { get; set; }
        public virtual DbSet<EMPLOYEE_TBL> EMPLOYEE_TBL { get; set; }
        public virtual DbSet<ORDERS_TBL> ORDERS_TBL { get; set; }
        public virtual DbSet<products_tbl> products_tbl { get; set; }
    }
}
