//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class products_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public products_tbl()
        {
            this.ORDERS_TBL = new HashSet<ORDERS_TBL>();
        }
    
        public string prodid { get; set; }
        public string proddesc { get; set; }
        public decimal cost { get; set; }
        public Nullable<decimal> cost_buy { get; set; }
        public Nullable<int> qty_in_stock { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERS_TBL> ORDERS_TBL { get; set; }
    }
}
